name: letterchase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4
  sqflite: ^2.4.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.2.3
  build_runner: ^2.8.0
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
